/// Flutter icons SweaterIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SweaterIcons
///      fonts:
///       - asset: fonts/SweaterIcons.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SweaterIcons {
  SweaterIcons._();

  static const _kFontFam = 'SweaterIcons';
  static const String? _kFontPkg = null;

  static const IconData search =
      IconData(0xf002, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check =
      IconData(0xf00c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData times =
      IconData(0xf00d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tint =
      IconData(0xf043, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_circle =
      IconData(0xf059, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left =
      IconData(0xf060, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right =
      IconData(0xf061, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus =
      IconData(0xf067, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xf0b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bars =
      IconData(0xf0c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_left =
      IconData(0xf104, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_right =
      IconData(0xf105, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sliders_h =
      IconData(0xf1de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash =
      IconData(0xf1f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData venus =
      IconData(0xf221, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mars =
      IconData(0xf222, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData external_link_alt =
      IconData(0xf35d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marker_alt =
      IconData(0xf3c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature_high =
      IconData(0xf769, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
